# Generated by Django 3.0 on 2022-08-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('purchase_or_sale', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale')], max_length=15)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('net', models.FloatField()),
                ('vat', models.FloatField()),
            ],
        ),
    ]
