# Generated by Django 3.0 on 2022-08-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='net',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='purchase_or_sale',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('sale', 'Sale')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='vat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
